[workspace]
resolver = "2"
members = [
    "a01_helloworld",
    "a02_variables",
    "a03_datatypes",
    "a04_function",
    "a05_control_flow",
    "a06_ownership",
    "a07_reference_borrow",
    "a08_structs",
    "a09_method_syntax",
    "a10_enums",
    "a11_opiton",
    "a12_match",
    "a13_package",
    "a14_collections",
    "a15_error",
    "a16_typeinto",
    "a17_minigrep",
    "a20_lifecycle",
    "a21_closure",
    "a22_my_macro",
    "a23_format_output",
    "a39_async_await",
    "a40_commandline",
    "a41_owner_borrow",
    "a50_serde",
    "a51_axum",
    "a52_chrono",
    "a53_log4",
    'algorithms',
    'at_ex',
    'chrono_ex',
    'clap_ex',
    'compression_ex',
    'config_ex',
    'crossbeam_ex',
    'cryptography_ex',
    'default_ex',
    'derive_more_ex',
    'dialoguer_ex',
    'dotenv_ex',
    'env_ex',
    'error_anyhow_ex',
    'error_ex',
    'ffi_ex',
    'hash_ex',
    'http_ex',
    'indicatif_ex',
    'iter_ex',
    'option_ex',
    'path_ex',
    'polars_ex',
    'prost_ex',
    'rand_ex',
    'result_ex',
    'semver_ex',
    'serde_ex',
    'logging_ex',
    'mem_ex',
    'once_cell_ex',
    'strum_ex',
    'tera_ex',
    'time_ex',
    'typed_builder_ex',
    'url_ex',
    'uuid_ex',
    'zip_ex'
]
