[package]
name = 'polars_ex'
version = '0.1.0'
edition = '2021'

[dependencies]
color-eyre = '0.6'
rand = "0.8.5"

[dependencies.reqwest]
version = '0.11'
features = ['blocking']

[dependencies.polars]
version = "0.25"
features = ["lazy", "strings", "concat_str"]
