[package]
name = "cryptography_ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
base64-url = "1.4.13"
data-encoding = "2.3.3"
hex = "0.4.3"
md5 = "0.7.0"
ring = "0.16.20"
