[package]
name = "a06_ownership"
version = "0.1.0"
authors = ["mo <thinkgo@aliyun.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
