[package]
name = "indicatif_ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.2"
indicatif = "0.17.1"
rand = "0.8.5"
